=== sordahl-ga/hapi-hl7overhttp-azurefuncs/src/site/resources/conf/constraint_analyzer/profiles/conformance.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY % Optionality "R | RE | O | C | CE | X">
<!ELEMENT Specification (ImpNote?, UseCase?, Conformance, Encodings, Message)>
<!ATTLIST Specification
	SpecName CDATA #REQUIRED
	OrgName CDATA #REQUIRED
	HL7Version CDATA #REQUIRED
	SpecVersion CDATA #IMPLIED
	Status CDATA #IMPLIED
	Role (Sender | Receiver) "Sender"
	HL7OID CDATA #IMPLIED
	ConformanceType (Implementation | Constrainable) #REQUIRED
>
<!ELEMENT UseCase (Actor | PreCondition | PostCondition | EventFlow | DerivativeEvent)*>
<!ELEMENT Actor (#PCDATA)>
<!ATTLIST Actor
	Name CDATA #REQUIRED
>
<!ELEMENT PreCondition (#PCDATA)>
<!ATTLIST PreCondition
	Name CDATA #REQUIRED
>
<!ELEMENT PostCondition (#PCDATA)>
<!ATTLIST PostCondition
	Name CDATA #REQUIRED
>
<!ELEMENT EventFlow (#PCDATA)>
<!ATTLIST EventFlow
	Name CDATA #REQUIRED
>
<!ELEMENT DerivativeEvent (#PCDATA)>
<!ATTLIST DerivativeEvent
	Name CDATA #REQUIRED
>
<!ELEMENT Conformance EMPTY>
<!ATTLIST Conformance
	AccAck (AL | NE | SU | ER) "NE"
	AppAck (AL | NE | SU | ER) "AL"
	StaticID CDATA #REQUIRED
	DynamicID CDATA #IMPLIED
	MsgAckMode (Immediate | Deferred) "Deferred"
>
<!ELEMENT Encoding (#PCDATA)>
<!ELEMENT Encodings (Encoding+)>
<!ELEMENT Message (Description?, Reference?, Segment, (SegGroup | Segment)*)>
<!ATTLIST Message
	MsgType CDATA #REQUIRED
	EventType CDATA #REQUIRED
	MsgStructID CDATA #REQUIRED
	OrderControl CDATA #IMPLIED
	EventDesc CDATA #REQUIRED
>
<!ELEMENT SegGroup (ImpNote?, Description?, Reference?, Predicate?, (SegGroup | Segment)+)>
<!ATTLIST SegGroup
	Name CDATA #REQUIRED
	LongName CDATA #REQUIRED
	Optionality (%Optionality;) #REQUIRED
	Min CDATA #REQUIRED
	Max CDATA "1"
>
<!ELEMENT Segment (ImpNote?, Description?, Reference?, Predicate?, Field+)>
<!ATTLIST Segment
	Name CDATA #REQUIRED
	LongName CDATA #IMPLIED
	Optionality (%Optionality;) #REQUIRED
	Min CDATA #REQUIRED
	Max CDATA "1"
>
<!ELEMENT Field (ImpNote?, Description?, Reference?, Predicate?, DataValues*, Component*)>
<!ATTLIST Field
	Name CDATA #REQUIRED
	Optionality (%Optionality;) #REQUIRED
	Min CDATA #REQUIRED
	Max CDATA "1"
	Datatype CDATA #REQUIRED
	Length CDATA #IMPLIED
	Table CDATA #IMPLIED
	ConstantValue CDATA #IMPLIED
	ItemNo CDATA #IMPLIED
>
<!ELEMENT Component (ImpNote?, Description?, Reference?, Predicate?, DataValues*, SubComponent*)>
<!ATTLIST Component
	Name CDATA #REQUIRED
	Optionality (%Optionality;) #REQUIRED
	Datatype CDATA #REQUIRED
	Length CDATA #IMPLIED
	Table CDATA #IMPLIED
	ConstantValue CDATA #IMPLIED
>
<!ELEMENT SubComponent (ImpNote?, Description?, Reference?, Predicate?, DataValues*)>
<!ATTLIST SubComponent
	Name CDATA #REQUIRED
	Optionality (%Optionality;) #REQUIRED
	Datatype CDATA #REQUIRED
	Length CDATA #IMPLIED
	Table CDATA #IMPLIED
	ConstantValue CDATA #IMPLIED
>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT ImpNote (Paragraph+)>
<!ELEMENT Paragraph (#PCDATA)>
<!ELEMENT Predicate (#PCDATA)>
<!ELEMENT Reference (#PCDATA)>
<!ELEMENT DataValues EMPTY>
<!ATTLIST DataValues ExValue CDATA #IMPLIED>

=== sordahl-ga/hapi-hl7overhttp-azurefuncs/src/site/resources/conf/constraint_analyzer/profiles/testADTExampleSegGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Specification SYSTEM "conformance.dtd">
<Specification SpecName="Constrainable - Constrained - Inbound ADT-ADT_A01" OrgName="Queen's University" HL7Version="2.3.1" SpecVersion="1.0" Status="active" ConformanceType="Constrainable" Role="Sender" HL7OID="">
<ImpNote><Paragraph>ADT_A01&#160;&#160;Constrainable Profile Example</Paragraph></ImpNote>
<Conformance AccAck="NE" AppAck="AL" StaticID="{ConfSig(1) Queen's University(1) 2.3.1(6) static-profile(1) ADT(3) A01(1) null(0) ADT_A01(3) 1.0(1) Sender(1)}" DynamicID="{ConfSig(1) Queen's University(1) 2.3.1(6) dynamic-profile(2) AccNE_AppAL(2) defer_mode_ack(1)}" MsgAckMode="Deferred"></Conformance>
<Encodings><Encoding>ER7</Encoding></Encodings>
<Message MsgType="ADT" EventType="A01" EventDesc="Admit / Visit notification" MsgStructID="ADT_A01">
<Description>"MSH,EVN,PID,PV1,{AL1}"</Description>
<Segment Name="MSH" LongName="message header segment" Optionality="R" Min="1" Max="1">
<Field Name="Field Separator"  Optionality="R" Min="1" Max="1" ItemNo="" Datatype="ST" Length="1"> <Reference>"11.6.1"</Reference><DataValues ExValue="|"/></Field>
<Field Name="Encoding Characters"  Optionality="R" Min="1" Max="1" ItemNo="" Datatype="ST" Length="4"><Reference>"11.2.2"</Reference><DataValues ExValue="^&amp;~\"/></Field>
<Field Name="Date/Time Of Message"  Optionality="R" Min="1" Max="1" ItemNo="" Datatype="TS" Length="26"><Reference>"11.2.7"</Reference><Component Name="Date/Time"  Optionality="R"  Datatype="NM" Length="26"><Description>"YYYYMMDD[HHHMM[SS[.SSSS]]][+-ZZZZ]"</Description><DataValues ExValue=""/></Component><Component Name="degree of precision" Optionality="X"  Datatype="ST" Length="1"><Description>"&quot;Retained for backward compatibility only&quot;"</Description> <DataValues ExValue=""/></Component></Field>
</Segment>
	<SegGroup Name = "test" LongName="Testing SegmentGroup" Optionality="R" Min="1" Max="1">
	<Segment Name="AL1" LongName="patient allergy information segment" Optionality="C"  Min="0" Max="10">
		<Predicate/>
		<Field Name="Set ID - AL1"  Optionality="R"   Min="1" Max="1" ItemNo="" Datatype="SI" Length="4"><Reference>"3.3.6.1"</Reference> <DataValues ExValue=""/></Field>
		<Field Name="Allergy Code/Mnemonic/Description"  Optionality="R"   Min="1" Max="1" ItemNo="" Datatype="CE" Length="60"><ImpNote>     <Paragraph>Maps to organization's Allergy Type values</Paragraph>     <Paragraph>table</Paragraph></ImpNote><Reference>"3.3.6.3"</Reference>
			<Component Name="identifier"  Optionality="R"  Datatype="ST" Length="5"   ><ImpNote>     <Paragraph>Allergy Code</Paragraph>     <Paragraph>Code not required for free text allergies.</Paragraph></ImpNote> <DataValues ExValue="54321"/></Component>
			<Component Name="text"  Optionality="R"  Datatype="ST" Length="30"   ><ImpNote>     <Paragraph>Allergy Description</Paragraph></ImpNote> <DataValues ExValue="Tree Mould"/></Component>
			<Component Name="name of coding system"  Optionality="X"  Datatype="ST" Length="3"   > <DataValues ExValue=""/></Component>
			<Component Name="alternate identifier"  Optionality="X"  Datatype="ST" Length="3"   ><DataValues ExValue=""/><SubComponent Name="identifier"  Optionality="O"  Datatype="ST" Length="0"/> </Component>
			<Component Name="alternate text"  Optionality="X"  Datatype="ST" Length="3"   > <DataValues ExValue=""/></Component>
			<Component Name="name of alternate coding system"  Optionality="X"  Datatype="ST" Length="3"   > <DataValues ExValue=""/></Component>
		</Field>
	</Segment>
	</SegGroup>
</Message>
</Specification>
